<?php

/**
 * implements hook_menu().
 */
function magic_menu_menu() {
  $items = array();

  $items['magic'] = array(
      'title' => 'A little magic',
      'page callback' => 'menu_magic_basic',
      'access callback' => 'user_access', //user access('access content')
      'access arguments' => array('access content'),
  );

  $items['magic/%'] = array(
      'title' => 'Even more magical',
      'page callback' => 'menu_magic_extra',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'menu_magic.extra.inc',
  );

  $items['user/%/magic'] = array(
      'title' => 'Magic',
      'description' => 'Magical magic for users',
      'page callback' => 'menu_magic_user_tab',
      'page arguments' => array(1),
      'access callback' => array('user_access'),
      'access arguments' => array('administer users'),
      'file' => 'menu_magic.user.inc',
      'type' => MENU_LOCAL_TASK,
  );

  $items['node/%/magic'] = array(
    'title' => 'Magic',
      'description' => 'Do amazing magical things',
      'page callback' => 'menu_magic_node_context',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'magic_menu.context.inc',
      'type' => MENU_LOCAL_TASK,
      'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

function menu_magic_basic() {
    $content = array();
    $content['raw_markup'] = array(
        '#type' => 'markup',
        '#markup' => '<p>' . t('This is magical').'</p>',
    );

    $variables = array(
        'path' => 'http://fakeimg.pl/450x500/',
        'alt' => t('alt for image'),
        'title' => t('This is title'),
    );

    $content['themed_data'] = array(
        '#type' => 'markup',
        '#markup' => theme('image', $variables),
        '#prefix' => '<div class="menu-magic-image">',
        '#suffix' => '</div>',
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'magic_menu') . '/magic_menu.css',
          ),
        ),
    );

    $content['renderable_element'] = array(
        '#theme' => 'item_list',
        '#type' => 'ol',
        '#title' => t('How do we know it\'s magic'),
        '#items' => array(
          t('lorem ipsum'),
          t('dolor'),
          t('sit amet'),
        ),
    );

    return $content;
}